### ISSUE TITLE
pandoc

### ISSUE THREAD

**Issue by mikkokotila** [Esukhia/bophono#6]
What is pandoc used for in this library? Given that we are just converting string to another string, it seems that no such package is needed?

Generally speaking, python packages should not have dependencies that are not python. When there is such a thing, it should be because a vitally important capability is impossible without such dependency. It should never be because of convenience or habit.

**Comment by eroux** [comment]
correct yes, it's probably there for historical reasons, feel free to remove it

**Comment by eroux** [comment]
fixed
